$(document).ready(function(){  
  $("li#onco").click(function(){
    $("#oncologists").show();
    $("#paediatricians").hide();
  });
  $("li#gynae").click(function(){
  $("#gynaecologists").show();
  $("#oncologists").hide();
  $("#paediatricians").hide();
  });
});   
